apiVersion: carto.run/v1alpa1
kind: Workload
metadata:
  name: java-function
  labels:
    apps.tanzu.vmware.com/workload-type: workload-type
    app.kubernetes.io/part-of: java-function
spec:
  build:
    env:
    - name: BP_FUNCTION
      value: functions.Handler
  source:
    git:
      url: git-source-url
      ref:
        branch: git-branch-name
